public with sharing class Uniquenumber {
	public void uniqueArray()
	{
		Integer[] myList = new List<Integer>{10, 20,10,10};
		for(integer i=0;i<=3;i++)
		{
			system.debug(+mylist[i]);
		}
			Set<Integer> s1 = new Set<Integer>(myList);
			system.debug(+s1);
			
	}
    
}
/*list<integer> arr_elem = new list<integer>();
		arr_elem.add(10);
		arr_elem.add(20);
		arr_elem.add(10);
		for(integer count=0;count >=3;count++)
		{
			System.debug(+arr_elem[count]);
			//set<integer>arr_elem2 = new set<integer>();
			//system.debug(+arr_elem2[count]);
		}*/